### ISSUE TITLE
remove scientific formatting

### ISSUE THREAD

**Issue by ctrl-Felix** [Interbloc-labs/tipbot#12]
`Successful Wthdrawal
ID:
eb7557c8-0dfc-4ec9-9b60-c6a66a4e3279
Receiver:
osmo1g35hcwttpfgqxmr828feg9lr37pjk4qzflr2ux
Hash:
2496500DFDDB56D3AD50CCAC067743E0FC9222E5FD555A8A3D1B452AA5C84808
Amount: 2e-05 OSMO
`

**Comment by ctrl-Felix** [comment]
Added a withdrawal limit and fixed formatting

**Comment by coldy-validator** [comment]
Sent 1e-06 $OSMO to @mikebarb

Scientific notation is back

**Comment by ctrl-Felix** [comment]
fixed
