### ISSUE TITLE
Small number handling & many decimals

### ISSUE THREAD

**Issue by ctrl-Felix** [Interbloc-labs/tipbot#9]
0.000001 or 0.9999999

**Comment by jasbanza** [comment]
Not sure if you know about this? https://docs.python.org/3/library/decimal.html

**Comment by jasbanza** [comment]
I'm not used to python, but I use something similar in JS... It's a life saver when it comes to working with money

Here's an overview of that library 
https://zetcode.com/python/decimal/

**Comment by ctrl-Felix** [comment]
switched to denom notation
